# Generated by Django 5.0.3 on 2024-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(default='Empty Complaint'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(default='UnassignedDepartment', max_length=150),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pendinng', max_length=50),
        ),
    ]
